services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./src/database/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  api:
    build: .
    container_name: node_api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DB_HOST=db # Usamos el nombre del servicio de la BD
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=3306
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Evita que node_modules local sobreescriba el del contenedor
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
